# Generated by Django 3.2.25 on 2024-10-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=100)),
                ('authorname', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('desc', models.TimeField()),
                ('editionyear', models.IntegerField()),
            ],
        ),
    ]
