# Generated by Django 3.2.25 on 2024-10-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_book_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Bookpdf',
            field=models.FileField(blank=True, upload_to='pdf'),
        ),
        migrations.AlterField(
            model_name='book',
            name='poster',
            field=models.ImageField(blank=True, upload_to='posters/'),
        ),
    ]
