# Generated by Django 3.2.25 on 2024-11-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0004_auto_20241018_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Bookpdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf'),
        ),
        migrations.AlterField(
            model_name='book',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/'),
        ),
    ]
