# Generated by Django 3.2.25 on 2024-11-05 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0005_auto_20241103_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='editionyear',
        ),
    ]
